apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hash-service-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
    - proxidize
  selector:
    matchLabels:
      app: hash-service
      component: hash
      release: prometheus
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 15s